name: Markdown Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: |
            **/*.md
            #jetbrains-plugin/build/**
            #vscode-extension/node_modules/**
